language: java

sudo: required
dist: trusty

install:
  - sudo add-apt-repository -y ppa:cwchien/gradle && sudo apt-get update && sudo apt-get install -qq gradle-2.9
  - gradle dependencies | stdbuf -o0 sed 's/.*/./g' | stdbuf -o0 tr -d '\n'; echo
  - ./buildSrc/src/deploy/bash/Install\ Doc.sh
  
script:
  - gradle build qc
  
after_failure:
  - gradle web || gradle web --info --stacktrace
  
after_success:
  - gradle cleanTmp
  - ./buildSrc/src/deploy/bash/Deploy\ SVN.sh

after_script:
  - ./buildSrc/src/deploy/bash/Deploy\ Web.sh