language: java

sudo: required
dist: trusty

install:
  - sudo add-apt-repository -y ppa:cwchien/gradle && sudo apt-get update && sudo apt-get install -qq gradle-2.9
  - gradle dependencies
  
script:
  - gradle srsinstall build qc || gradle build qc --info --stacktrace
  
after_script:
  - gradle web || gradle web --info --stacktrace
  - ./buildSrc/src/deploy/bash/Deploy\ Web.sh
  
after_success:
  - ./buildSrc/src/deploy/bash/Deploy\ SVN.sh
